### ISSUE TITLE
Not working fine after locking screen and unlock

### ISSUE THREAD

**Issue by luca-viggiani** [DreaminginCodeZH/gnome-shell-extension-transparent-top-bar#2]
When Chrome is the only app running, the transparency of the top bar doesn't change when maximizing / unmaximizing Chrome window.

**Comment by DreaminginCodeZH** [comment]
Cannot reproduce on Arch Linux, GNOME Shell 3.32.1 and Google Chrome 74.0.3729.108.

Anyway, this is the original implementation in 3.30 and I only did a bit of refactoring to make it an extension. All that was working in 3.30 should also work on 3.32.

**Comment by luca-viggiani** [comment]
Hi, please look at [this video](https://drive.google.com/open?id=1mdCUB7PUZeoPg-8sCiF78VJamoTza1qf). I'm on Arch Linux too with same GS version...
I've also tried disabling all the other extension but nothing changes...

**Comment by luca-viggiani** [comment]
I forgot to mention that I'm on Wayland session

**Comment by luca-viggiani** [comment]
...ok that's weird... I set Chrome to use the system title bar and the issue is gone. Then I reset Chrome not to use the system title bar (like in the video) and I expected the issue to be back but now it's working fine!

Just to summarize:
Chrome with custom title bar -> issue ON
Chrome with system title bar -> issue gone
Chrome back to custom title bar -> issue gone
Even after restart. I'll play around a little bit more and if the issue will not show up anymore I'll close the bug.

**Comment by DreaminginCodeZH** [comment]
Cannot reproduce on Wayland and Chrome with custom title bar.

**Comment by luca-viggiani** [comment]
Hi, I've found a way to reproduce:

1) Open Chrome and maximize the window
2) Lock the screen
3) Unlock the screen
4) Unmaximize Chrome: the issue is there. The top bar stay black as shown [here](https://drive.google.com/open?id=1mdCUB7PUZeoPg-8sCiF78VJamoTza1qf)

**Comment by DreaminginCodeZH** [comment]
Yeah, this is reproducible. Now I wonder why this happens... I'm no GNOME expert either.

**Comment by DreaminginCodeZH** [comment]
It's not only Chrome - any window that's open before locking the screen doesn't affect the top bar any more

**Comment by DreaminginCodeZH** [comment]
Thanks for reporting this and giving the reproduction steps!

The original implementation has the same lifecycle as the GNOME Shell itself so it didn't handle existing windows, but now we need to handle it when enabling the extension. I'll upload a new version for review and hopefully it will get approved soon.

**Comment by A-Hussein-M** [comment]
this is back, crashes randomly after restoring from suspend, still can't figure out how to reproduce.
forces me to re-login in order to get it back working.
GNOME 3.36.2 fedora 32

**Comment by zhanghai** [comment]
Crashing is a different thing than not handling existing windows, but I still couldn't reproduce it (I'm using it daily). I may take a look if you can attach a stacktrace, e.g. via `lg`.

**Comment by A-Hussein-M** [comment]
> Crashing is a different thing than not handling existing windows, but I still couldn't reproduce it (I'm using it daily). I may take a look if you can attach a stacktrace, e.g. via `lg`.

My bad, that is totally unrelated to the crash I am experiencing. It crashed now for the first time since my last comment, I will create an issue with the error reported by `lg`, please let me know you need any further information.
